---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: srenkserver
# description will be included in the image's metadata
description: Макаронный сыр

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-coreos
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - caddy
        - micro

  - type: systemd
    system:
      enabled:
        - caddy.service

  - type: kargs
    arch: x86_64
    kargs:
      - thinkpad_acpi.fan_control=1
      - mitigations=off


  - type: signing # this sets up the proper policy & signing files for signed images to work fully

